/**
 * Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.  The ASF licenses this file to you under the Apache License, Version
 * 2.0 (the "License"); you may not use this file except in compliance with the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions
 * and limitations under the License.
 */

package org.apache.storm.serialization;

import com.esotericsoftware.kryo.io.Input;
import java.io.IOException;
import java.util.List;
import java.util.Map;
import org.apache.storm.Config;
import org.apache.storm.task.GeneralTopologyContext;
import org.apache.storm.tuple.MessageId;
import org.apache.storm.tuple.TupleImpl;
import org.apache.storm.utils.ObjectReader;
import org.apache.storm.utils.Utils;

public class KryoTupleDeserializer implements ITupleDeserializer {
    private static final Integer DEFAULT_MAX_DECOMPRESSED_BYTES = 100 * 1024 * 1024;
    private final GeneralTopologyContext context;
    private final KryoValuesDeserializer kryo;
    private final SerializationFactory.IdDictionary ids;
    private final Input kryoInput;
    private final int maxZstdDecompressedBytes;

    public KryoTupleDeserializer(final Map<String, Object> conf, final GeneralTopologyContext context) {
        kryo = new KryoValuesDeserializer(conf);
        this.context = context;
        ids = new SerializationFactory.IdDictionary(context.getRawTopology());
        kryoInput = new Input(1);
        maxZstdDecompressedBytes = ObjectReader.getInt(conf.get(Config.STORM_COMPRESSION_ZSTD_MAX_DECOMPRESSED_BYTES), DEFAULT_MAX_DECOMPRESSED_BYTES);
    }

    @Override
    public TupleImpl deserialize(byte[] ser) {
        try {
            byte[] dataToProcess = ser;

            /*
             * The official Zstandard magic header bytes (0x28, 0xB5, 0x2F, 0xFD), used to detect compressed payloads
             * with zero network overhead. This approach is mathematically immune to protocol collisions because the
             * initial bytes of an uncompressed Storm tuple are generated by Kryo's variable-length integer encoding
             * (Varint) representing the positive {@code sourceTask} and {@code streamId}. While a Task ID of 40 can
             * match the first Zstd byte ({@code 0x28}), the second Zstd byte ({@code 0xB5}, which has a Most Significant
             * Bit of 1) cannot collide with the subsequent Stream ID, as small positive Varints strictly require a Most
             * Significant Bit of 0. This structural incompatibility creates a unique binary fingerprint, allowing the
             * deserializer to reliably distinguish data streams without allocating extra header bytes.
             */
            if (Utils.ZstdUtils.isZstd(dataToProcess)) {
                dataToProcess = Utils.ZstdUtils.decompress(dataToProcess, this.maxZstdDecompressedBytes);
            }

            kryoInput.setBuffer(dataToProcess);
            int taskId = kryoInput.readInt(true);
            int streamId = kryoInput.readInt(true);
            String componentName = context.getComponentId(taskId);
            String streamName = ids.getStreamName(componentName, streamId);
            MessageId id = MessageId.deserialize(kryoInput);
            List<Object> values = kryo.deserializeFrom(kryoInput);
            return new TupleImpl(context, values, componentName, taskId, streamName, id);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }
}
