(ns backtype.storm.cgroup.constant)

(def CPU-HIERARCHY-DIR "/cgroup/cpu")
(def MEMORY-HIERARCHY-DIR "/cgroup/memory")
(def CGROUP-STATUS-FILE "/proc/cgroups")
(def MOUNT-STATUS-FILE "/proc/mounts")

(def TASKS "/tasks")
(def CPU-SHARES "/cpu.shares")
(def CPU-RT-RUNTIME-US "/cpu.rt_runtime_us")
(def CPU-RT-PERIOD-US "/cpu.rt_period_us")
(def CPU-CFS-PERIOD-US "/cpu.cfs_period_us")
(def CPU-CFS-QUOTA-US "/cpu.cfs_quota_us")
(def CPU-STAT "/cpu.stat")
(def MEMORY-STAT "/memory.stat")
(def MEMORY-USAGE-IN-BYTES "/memory.usage_in_bytes")
(def MEMORY-MEMSW-USAGE-IN-BYTES "/memory.memsw.usage_in_bytes")
(def MEMORY-MAX-USAGE-IN-BYTES "/memory.max_usage_in_bytes")
(def MEMORY-MEMSW-MAX-USAGE-IN-BYTES "/memory.memsw.max_usage_in_bytes")
(def MEMORY-LIMIT-IN-BYTES "/memory.limit_in_bytes")
(def MEMORY-MEMSW-LIMIT-IN-BYTES "/memory.memsw.limit_in_bytes")
(def MEMORY-FAILCNT "/memory.failcnt")
(def MEMORY-MEMSW-FAILCNT "/memory.memsw.failcnt")
(def MEMORY-FORCE-EMPTY "/memory.force_empty")
(def MEMORY-SWAPPINESS "/memory.swappiness")
(def MEMORY-USE-HIERARCHY "/memory.use_hierarchy")
(def MEMORY-OOM-CONTROL "/memory.oom_control")
(def NET-CLS-CLASSID "/net_cls.classid")

(def SUBSYSTEM-TYPE #{:blkio :cpu :cpuacct :cpuset :devices :freezer :memory :perf_event :net_cls :net_prio})
